server:
  port: 8004

# 服务别名---zookeeper注册中心名称
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      # zookeeper 配置
      connect-string: 192.168.18.142:2181
      max-retries: 10
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud-study-payment?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root